### ISSUE TITLE
`pip install` isn't run?

### ISSUE THREAD

**Issue by AlecTaylor** [Strider-CD/strider-python#9]
The help text in Strider CD says it'll run:

    virtualenv, pip install, ./setup.py test or py.test

But going through the interface, it doesn't look like `pip install` runs.

Please fix. Thanks

**Comment by knownasilya** [comment]
It is in the prepare phase, there is no UI for it.

See here: https://github.com/Strider-CD/strider-python/blob/master/webapp.js#L17
